# Generated by Django 4.1.4 on 2023-07-10 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chbackend', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
